Enhance setup script with error handling
Added error handling and improved script robustness.

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set -e # Exit immediately if a command exits with a non-zero status
+
 # pre-requisites
 # https://docs.nvidia.com/datacenter/cloud-native/openshift/latest/steps-overview.html
 # 1. Install the Node Feature Discovery operator
@@ -21,7 +23,7 @@ usage_and_exit () {
 # Function: error, print usage and exit
 error_and_exit () {
     echo
-    echo $1
+    echo "Review above logs, resolve and try again."
     echo
     echo "To clean up for another attempt, use:"
     echo
@@ -29,6 +31,9 @@ error_and_exit () {
     echo
     exit 1
 }
+
+# Error function on ERR signal
+trap 'error_handler' ERR
 
 # Validate a project name, and only that, is included
 if [ $# -lt 1 ]; then
